### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by vannizhang** [vannizhang/vessel-traffic#32]
- [x] Add reference layer (https://arcgis-content.maps.arcgis.com/apps/mapviewer/index.html?layers=805e3b2cc1384c2d97671d30d98efe5e)
- [x] Update the way to determine the size of zip file to download (https://github.com/vannizhang/vessel-traffic/blob/dev/src/components/DownloadScreen/DownloadScreen.tsx#L61)
- [x] restore user selected feature from URL hash params
